[package]
name = "cookie-rs"
version = "0.2.1"
repository = "https://github.com/magwoo/cookie-rs"
description = "library for working with HTTP cookies"
keywords = ["cookie", "http", "web"]
readme = "./README.md"
license = "MIT"
edition = "2021"

[dependencies]

