[package]
name = "cookie-rs"
version = "0.0.1-alpha"
repository = "https://github.com/magwoo/cookie-rs"
description = "In work"
keywords = ["cookie", "http", "web"]
license = "MIT"
edition = "2021"

[dependencies]

